title: "The Python Fake Book for Making Things"
description: |
  A quick recipe list of common Python programming patterns for data wrangling and creating stuff.
author: Dan Nguyen
image_url: https://middlemanapp.com/images/middleman-logo.svg
baseurl: "http://python.makenfake.com"




# services:
#   google_analytics:
#     id: UA-57356732-1
